apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: back-np
spec:
  # Selects the Backend Pods
  podSelector:
    matchLabels:
      app: back-deployment
  policyTypes:
    - Ingress
    - Egress

  # --- INGRESS RULES ---
  ingress:
    # 1. Allow traffic from Frontend Pods
    - from:
        - podSelector:
            matchLabels:
              app: front-deployment
      ports:
        - protocol: TCP
          port: 8080
          
  # --- EGRESS RULES ---
  egress:
    # 1. Allow outbound traffic to the Database Pods on port 3306
    - to:
        - podSelector:
            matchLabels:
              app: database-deployment
      ports:
        - protocol: TCP
          port: 3306
