apiVersion: v1
kind: Secret
metadata:
  name: {{ include "database.fullname" . }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
type: Opaque
data:
  rootpassword: cm9vdA==
  dbpassword: MTIzNDU2