apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pv-claim 
  labels:
    app: database-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi